config/routes.rb
Rails.application.routes.draw do
  resources :past_requests
  resources :admins
  get 'sessions/new'

  root                   'requests#index'
  get       'login'   => 'sessions#new'
  post      'login'   => 'sessions#create'
  delete    'logout'  => 'sessions#destroy'
  match 'past_requests/:id/archive' => 'past_requests#update', as: :past_requests_archive, via: [:get, :post]
  resources :requests
  resources :students

end

app/models/past_request.rb
class PastRequest < ActiveRecord::Base
	belongs_to :student
end

app/controllers/past_requests_controller.rb
include ActionView::Helpers::DateHelper

class PastRequestsController < ApplicationController
  before_action :set_past_request, only: [:show, :edit, :update, :destroy]

  # GET /past_requests
  # GET /past_requests.json
  def index
    @past_requests = PastRequest.all.reverse
  end

  # GET /past_requests/1
  # GET /past_requests/1.json
  def show
  end

  # GET /past_requests/new
  def new
    @past_request = PastRequest.new
  end

  # GET /past_requests/1/edit
  def edit
  end

  # POST /past_requests
  # POST /past_requests.json
  def create
    @past_request = PastRequest.new(past_request_params)

    respond_to do |format|
      if @past_request.save
        format.html { redirect_to @past_request, notice: 'Past request was successfully created.' }
        format.json { render :show, status: :created, location: @past_request }
      else
        format.html { render :new }
        format.json { render json: @past_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /past_requests/1
  # PATCH/PUT /past_requests/1.json
  def update
    respond_to do |format|
      @past_request.received_help = true
      if @past_request.update(past_request_params)
        format.html { redirect_to requests_path, notice: "You spent #{time_ago_in_words(Time.now - (Time.now - @past_request.created_at), include_seconds: true)}" }
        format.json { render :show, status: :ok, location: @past_request }
      else
        format.html { render :edit }
        format.json { render json: @past_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /past_requests/1
  # DELETE /past_requests/1.json
  def destroy
    @past_request.destroy
    respond_to do |format|
      format.html { redirect_to past_requests_url, notice: 'Past request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_past_request
      @past_request = PastRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def past_request_params
      params.permit(:id, :student_id, :removed_by, :time_waited, :received_help)
    end
end

app/helpers/past_requests_helper.rb
module PastRequestsHelper
end

app/views/past_requests/_form.html.erb
<% content_for :refresh_tag do %>  
  <%= form_for(@past_request) do |f| %>
    <% if @past_request.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@past_request.errors.count, "error") %> prohibited this past_request from being saved:</h2>

        <ul>
        <% @past_request.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :student_id %><br>
      <%= f.number_field :student_id %>
    </div>
    <div class="field">
      <%= f.label :removed_by %><br>
      <%= f.text_field :removed_by %>
    </div>
    <div class="field">
      <%= f.label :time_waited %><br>
      <%= f.text_field :time_waited %>
    </div>
    <div class="field">
      <%= f.label :received_help %><br>
      <%= f.check_box :received_help %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
<% end %>

app/views/past_requests/edit.html.erb
<h1>Editing Past Request</h1>

<%= render 'form' %>

<%= link_to 'Show', @past_request %> |
<%= link_to 'Back', past_requests_path %>

app/views/past_requests/index.html.erb
<% content_for :refresh_tag do %>  
  <p id="notice"><%= notice %></p>

  <div class="container">
    <h1>List of Past Requests</h1>

    <table class="table-hover table-striped table" frame="border">
      <thead>
        <tr>
          <th style="font-size:20px">Student</th>
          <th style="font-size:20px">Removed by</th>
          <th style="font-size:20px">Time waited</th>
          <th style="font-size:20px">Received help</th>
          <th style="font-size:20px">Help Duration</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @past_requests.each do |past_request| %>
          <% if past_request.time_waited > 3600 %>
            <tr class="warning">
          <% else %>
            <tr>
          <% end %>
            <% student = Student.find_by(id_num: past_request.student_id) %>
            <% admin = Admin.where(admin_id: past_request.removed_by).take %>
            <td style="font-size:20px"><%= student.name %></td>
            <% if admin %>
              <td style="font-size:20px"><%= admin.name %></td>
            <% else %>
              <td style="font-size:20px"><%= "Self" %></td>
            <% end %>
            <td style="font-size:20px"><%= "#{distance_of_time_in_words(past_request.created_at, past_request.created_at - past_request.time_waited)}" %></td>
            <td style="font-size:20px"><%= past_request.received_help %></td>
            <td style="font-size:20px"><%= "#{distance_of_time_in_words(past_request.updated_at, past_request.created_at)}" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/past_requests/new.html.erb
<h1>New Past Request</h1>

<%= render 'form' %>

<%= link_to 'Back', past_requests_path %>

app/views/past_requests/show.html.erb
<% content_for :refresh_tag do %>	
	<p id="notice"><%= notice %></p>

  <div class="container">
  	<br>
		<p style="font-size:30px">
		  <strong>Student:</strong>
		  <% student = Student.find_by(id_num: @past_request.student_id) %>
		  <%= student.name %>
		</p>
    <br>
		<p style="font-size:20px">
		  <strong>Removed by:</strong>
		  <% if @past_request.student_id == @past_request.removed_by %>
		    <%= "Self" %>
		  <% else %>
		    <% admin = Admin.find_by(admin_id: @past_request.removed_by) %>
		    <%= admin.name %>
		  <% end %>
		</p>
    <br>
		<p style="font-size:20px">
		  <strong>Time waited:</strong>
		  <%= "#{time_ago_in_words(@past_request.created_at - @past_request.time_waited)}" %>
		</p>
		<br>

		<%= link_to "/past_requests/#{@past_request.id}/archive", class: 'btn btn-primary' do %>
		  <i title="Finished" class="glyphicon glyphicon-thumbs-up"></i>
		<% end %>
	</div>
<% end %>