config/routes.rb
Rails.application.routes.draw do
  resources :past_requests
  resources :admins
  get 'sessions/new'

  root                   'requests#index'
  get       'login'   => 'sessions#new'
  post      'login'   => 'sessions#create'
  delete    'logout'  => 'sessions#destroy'
  match 'past_requests/:id/archive' => 'past_requests#update', as: :past_requests_archive, via: [:get, :post]
  resources :requests
  resources :students

end

app/views/admins/_form.html.erb
<div class="col-md-6">  
  <%= form_for(@admin) do |f| %>
    <% if @admin.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

        <ul>
        <% @admin.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :id %><br>
      <%= f.number_field :admin_id, class: 'form-control' %>
    </div>
    <div class="field">
      <%= f.label :password %><br>
      <%= f.text_field :password, class: 'form-control' %>
    </div>
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="field">
      <%= f.label :authorized %><br>
      <%= f.password_field :authorized, class: 'form-control' %>
    </div>
    <div class="actions">
      <%= f.submit "Create", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/admins/edit.html.erb
<h1>Editing Admin</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Back', admins_path %>

app/views/admins/index.html.erb
<% content_for :refresh_tag do %>
  <p id="notice"><%= notice %></p>

  <div class="container">
    <h1>List of Admins <%= link_to new_admin_path, class: 'btn btn-md btn-success' do %>
      <i title="Add Admin" class="glyphicon glyphicon-plus"></i>
    <% end %></h1>

    <table class="table-hover table-striped table" frame="border">
      <thead>
        <tr class="active">
          <th style="font-size:20px">Name</th>
          <th style="font-size:20px">Students Helped</th>
          <th style="font-size:20px">Average Help Time</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @admins.each do |admin| %>
          <tr>
            <td style="font-size:20px"><%= admin.name %></td>
            <% past_requests = PastRequest.where("received_help = ? AND removed_by >= ?", true, admin.admin_id) %>
            <% avg_duration = 0 %>
            <% past_requests.each do |past_request| %>
              <% avg_duration += (past_request.updated_at - past_request.created_at) %>
            <% end %>
            <% if past_requests.size > 0 %>
              <% avg_duration /= past_requests.size %>
            <% end %>
            <td style="font-size:20px"><%= past_requests.size %></td>
            <td style="font-size:20px"><%= "#{distance_of_time_in_words(Time.now, Time.now - avg_duration)}" %></td>
            <td><%= link_to admin, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' do %>
              <i title="Delete Admin" class="glyphicon glyphicon-remove"></i>
            <% end %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>
  </div>
<% end %>

app/views/admins/new.html.erb
<% content_for :refresh_tag do %>	
	<div class="container">	
		<h1>New Admin</h1>

		<%= render 'form' %>
  </div>
<% end %>

app/views/admins/show.html.erb
<% content_for :refresh_tag do %>
	<p id="notice"><%= notice %></p>

	<p>
	  <strong>Admin ID:</strong>
	  <%= @admin.admin_id %>
	</p>

	<p>
	  <strong>Name:</strong>
	  <%= @admin.name %>
	</p>

	<%= link_to 'Edit', edit_admin_path(@admin) %> |
	<%= link_to 'Back', admins_path %>
<% end %>