config/routes.rb
Rails.application.routes.draw do
  resources :past_requests
  resources :admins
  get 'sessions/new'

  root                   'requests#index'
  get       'login'   => 'sessions#new'
  post      'login'   => 'sessions#create'
  delete    'logout'  => 'sessions#destroy'
  match 'past_requests/:id/archive' => 'past_requests#update', as: :past_requests_archive, via: [:get, :post]
  resources :requests
  resources :students

end

app/models/student.rb
class Student < ActiveRecord::Base
	validates_presence_of :name
	validates :id_num,
						presence: true,
						uniqueness: true
	has_one :request
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    unless session[:admin]
      flash[:notice] = "You do not have permission for that"
      redirect_to "/requests"
    end
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)
    @student.password = (0...10).map { (97 + rand(26)).chr }.join
    session[:id] = @student.id_num
    session[:name] = @student.name

    respond_to do |format|
      if @student.save
        format.html { redirect_to requests_path, notice: "Your password is: #{@student.password}" }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :id_num)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<div class="col-md-6">  
  <%= form_for(@student) do |f| %>
    <% if @student.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

        <ul>
        <% @student.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="field">
      <%= f.label :id_num %><br>
      <%= f.number_field :id_num, class: 'form-control' %>
    </div>
    <div class="actions">
      <%= f.submit "Create", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<% content_for :refresh_tag do %>  
  <p id="notice"><%= notice %></p>

  <div class="container">
    <h1>List of Students</h1>

    <table class="table-hover table-striped table" frame="border">
      <thead>
        <tr class="active">
          <th style="font-size:20px">Name</th>
          <th style="font-size:20px">Id num</th>
          <th style="font-size:20px">Requests</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @students.each do |student| %>
          <% requests = PastRequest.where(student_id: student.id_num) %>
          <% if requests.size > 20 %>
            <tr class="danger">
          <% elsif requests.size > 10 %>
            <tr class="warning">
          <% else %>
            <tr>
          <% end %>
            <td style="font-size:20px"><%= student.name %></td>
            <td style="font-size:20px"><%= student.id_num %></td>
            <td style="font-size:20px"><%= requests.size %></td>
            <td><%= link_to student, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' do %>
              <i title="Delete Student" class="glyphicon glyphicon-remove"></i>
            <% end %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>
  </div>
<% end %>

app/views/students/new.html.erb
<% content_for :refresh_tag do %>
	<div class="container">
		<h1>New Student</h1>

		<%= render 'form' %>
  </div>
<% end %>

app/views/students/show.html.erb
<% content_for :refresh_tag do %>	
	<p id="notice"><%= notice %></p>

	<p>
	  <strong>Name:</strong>
	  <%= @student.name %>
	</p>

	<p>
	  <strong>Id num:</strong>
	  <%= @student.id_num %>
	</p>

	<%= link_to 'Edit', edit_student_path(@student) %> |
	<%= link_to 'Back', students_path %>
<% end %>