config/routes.rb
Rails.application.routes.draw do
  resources :past_requests
  resources :admins
  get 'sessions/new'

  root                   'requests#index'
  get       'login'   => 'sessions#new'
  post      'login'   => 'sessions#create'
  delete    'logout'  => 'sessions#destroy'
  match 'past_requests/:id/archive' => 'past_requests#update', as: :past_requests_archive, via: [:get, :post]
  resources :requests
  resources :students

end

app/models/request.rb
class Request < ActiveRecord::Base
	belongs_to :student
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:show, :edit, :update, :destroy]
  before_action :require_login

  # GET /requests
  # GET /requests.json
  def index
    @requests = Request.all
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
  end

  # GET /requests/new
  def new
    @request = Request.new
  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests
  # POST /requests.json
  def create
    hash = params[:post]
    student_id = hash[:student_id].to_i

    # check if student already has request submitted
    if Request.where(student_id: student_id).size > 0
      respond_to do |format|
        format.html { redirect_to Request.where(student_id: student_id).take, notice: 'You already have this request:' }
        format.json { render :show, status: 400 }
      end
    # check that student is registered
    elsif Student.where(id_num: student_id).size == 0
      respond_to do |format|
        format.html { redirect_to requests_path, notice: "Invalid ID number: #{student_id}" }
        format.json { render :show, status: 400 }
      end
    # create request
    else
      @request = Request.new(request_params)
      @request.student_id = student_id

      respond_to do |format|
        if @request.save
          format.html { redirect_to '/requests', notice: 'Request was successfully created.' }
          format.json { render :show, status: :created, location: @request }
        else
          format.html { render :new }
          format.json { render json: @request.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /requests/1
  # PATCH/PUT /requests/1.json
  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to @request, notice: 'Request was successfully updated.' }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { render :edit }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    if !session[:admin] && @request && session[:id] != @request.student_id
      flash[:notice] = "You do not have permission to remove this request"
      redirect_to(requests_path)
    elsif params[:helped]
      if Request.where(id: params[:id]).count > 0
        student = Student.where(id_num: @request.student_id).take

        past = PastRequest.create(student_id: student.id_num,
                           removed_by: session[:id],
                           time_waited: calc_wait(@request.created_at),
                           received_help: false)

        @request.destroy
        respond_to do |format|
          format.html { redirect_to past, notice: "Request for #{student.name} was removed." }
          format.json { head :no_content }
        end
      else
        respond_to do |format|
          format.html { redirect_to requests_url, notice: "Request already removed." }
          format.json { head :no_content }
        end
      end
    else
      if Request.where(id: params[:id]).count > 0
        student = Student.where(id_num: @request.student_id).take

        PastRequest.create(student_id: student.id_num,
                           removed_by: session[:id],
                           time_waited: calc_wait(@request.created_at),
                           received_help: false)

        @request.destroy
        respond_to do |format|
          format.html { redirect_to requests_url, notice: "Request for #{student.name} was removed." }
          format.json { head :no_content }
        end
      else
        respond_to do |format|
          format.html { redirect_to requests_url, notice: "Request already removed." }
          format.json { head :no_content }
        end
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = nil
      if Request.where(id: params[:id]).count > 0
        @request = Request.find(params[:id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params.permit(:student_id)
    end

    def require_login
      unless session[:id]
        flash[:notice] = "You must log in first"
        redirect_to "/login"
      end
    end

    def calc_wait(created_at)
      Time.now - created_at
    end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_form.html.erb
<div class="col-md-6">  
  <%= form_for(@request, as: :post) do |f| %>
    <% if @request.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@request.errors.count, "error") %> prohibited this request from being saved:</h2>

        <ul>
        <% @request.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label "ID Number" %><br>
      <%= f.number_field :student_id, :value => session[:id], class: 'form-control' %>
    </div>
    <div class="actions">
      <%= f.submit "Submit", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/requests/edit.html.erb
<h1>Editing Request</h1>

<%= render 'form' %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

app/views/requests/index.html.erb
<% content_for :refresh_tag do %>
  <meta http-equiv="refresh" content="10">
  <p id="notice"><%= notice %></p>

  <div class="container">
    <div class="row">
      <div class="col-xs-9" style="text-align:center">
        <h1>Help Queue</h1>
        <% if session[:admin] %>
          <h3><%= link_to "Admin Account", admins_path, class: 'btn btn-link', style: 'font-size:25px' %> </h3>
        <% else %>
          <% last_five_requests = PastRequest.where("received_help = ? AND created_at >= ?", true, Time.zone.now.beginning_of_day).order(created_at: :desc).limit(5) %>
          <% avg_wait = 0 %>
          <% if last_five_requests.size > 0 %>
            <% last_five_requests.each do |past_request| %>
              <% avg_wait += past_request.time_waited %>
            <% end %>
            <% avg_wait /= last_five_requests.size %>
          <% end %>
          <h3><%= "Average Wait Time: #{time_ago_in_words(Time.now - avg_wait, include_seconds: true)} (last 5)" %></h3>
        <% end %>
      </div>
      <div class="col-xs-3">
        <h3><%= "Welcome #{session[:name]} " %></h3>
        <div class="row" style="position:static">
          <%= link_to '/logout', method: :delete, class: 'btn btn-link btn-lg' do %>
              <i title="Logout" class="glyphicon glyphicon-log-out"></i>
          <% end %>
          <% if !session[:admin] %>
            <%= link_to new_request_path, class: 'btn btn-success btn-xs' do %>
              <i title="Submit Request" class="glyphicon glyphicon-plus"></i>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>

    <table class="table-hover table" frame="border">
      <thead>
        <tr class="active">
          <th style="font-size:20px">Student</th>
          <th style="font-size:20px">Wait Time</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @requests.each_with_index do |request, index| %>
          <% student = Student.where(id_num: request.student_id).take %>
          <% if session[:id] == student.id_num %>
            <tr class="info">
          <% elsif index < 5 %>
            <tr class="success">
          <% else %>
            <tr>
          <% end %>
            <td><%= link_to student.name, request, class: 'btn btn-link btn-xs', style: 'font-size:20px' %></td>
            <td style="font-size:20px"><%= "#{time_ago_in_words(request.created_at, include_seconds: true)}" %></td>
            <td><% if session[:id] == request.student_id || session[:admin] %>
              <%= link_to request, method: :delete, class: 'btn btn-danger btn-xs' do %>
                <i title="Remove Request" class="glyphicon glyphicon-remove"></i><% end %>
            <% end %></td>
            <% if session[:admin] %>
              <td><%= link_to request_path(request, helped: true), method: :delete, class: 'btn btn-success btn-xs' do %>
                <i title="Help Student" class="glyphicon glyphicon-ok"></i><% end %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/requests/new.html.erb
<% content_for :refresh_tag do %>
  <meta http-equiv="refresh" content="15;url=/requests">
  <div class="container">
		<h1>New Request</h1>

		<%= render 'form' %>
	</div>
<% end %>

app/views/requests/show.html.erb
<% content_for :refresh_tag do %>
	<p id="notice"><%= notice %></p>

  <div class="container">
		<p style="font-size:20px">
		  <strong>Student:</strong>
		  <% name = Student.where(id_num: @request.student_id).take.name %>
		  <%= name %>
		</p>
		<br>
		<p style="font-size:20px">
			<strong>Created:</strong>
		  <%= "#{time_ago_in_words(@request.created_at, include_seconds: true)}" + " ago" %>
		</p>
		<br>

		<%= link_to requests_path, class: 'btn btn-primary' do %>
		  <i title="Back" class="glyphicon glyphicon-arrow-left"></i>
		<% end %>
	</div>
<% end %>